#import "template/template.typ": *

#show: tultemplate2.with(
  lang: "en",
  title: (en: [Technical documentation of the Typst TUL template]),
  author: ([Ondřej Mekina], [Matěj Žucha]),
)

#profile("release")

= Build information

This document was built on #datetime.today().display("[year]-[month]-[day]").
#highlight[The information in this document can have discrepancies with older template versions.]
If you have a template generated by the generator or downloaded as a minimal build, check
the timestamp in `template/build_date.txt`.

= Minimal build for offline usage

If you wish to obtain a directory with just the template (without other generated files), download
the minimal build from https://typst.tul.cz/tultemplate2_minimal.zip.
#highlight[This option, however, is not recommended for begginers.]

`tultemplate2_minimal.zip` is an automatically generated file with the most recent stable template
version built for direct usage.

For automatic build you can use the following _Makefile_
(with the following tools available system-wide: _typst_, _wget_ and _unzip_).

#raw(read("./minimal.mk"), block: true, lang: "make")

This file is also available from the template repository (https://git.zumepro.cz/tul/tultemplate2)
under filename `minimal.mk`.

= Source code and build sources

The template repo isn't the only source to build all the tools that the users will work with.
Bellow, you can see a quick overview of how the newest template version, examples and the generator
is built.

== Template toolchain overview

#v(.5em)

#import "@preview/fletcher:0.5.8" as fletcher

#let template = "https://git.zumepro.cz/tul/tultemplate2"
#let generator = "https://git.zumepro.cz/tul/tultemplategen"
#let much_pdf_tools = "https://git.zumepro.cz/ondrej.mekina/much_pdf_tools"
#let theses = "https://git.zumepro.cz/tul/tultemplate_theses"
#let stagspider = "https://git.zumepro.cz/tul/tultemplate_stagspider"
#let htmltypst = "https://git.zumepro.cz/ondrej.mekina/htmltypst"
#let web = "https://git.zumepro.cz/tul/tultemplate-web"

#align(center, {
  fletcher.diagram(
    fletcher.node(
      (-1, -1),
      link(much_pdf_tools)[pdf tools],
      shape: fletcher.shapes.rect,
      stroke: black,
      inset: .5em,
    ),
    fletcher.node(
      (1, -1),
      text([Typst], size: .8em),
      inset: .5em,
    ),
    fletcher.node(
      (0, 0),
      link(template, text([tultemplate2], size: 1.5em)),
      shape: fletcher.shapes.rect,
      stroke: black,
      inset: 1em,
    ),
    fletcher.edge((-1, -1), (0, 0), "-|>"),
    fletcher.edge((1, -1), (0, 0), "--|>"),
    fletcher.edge("-|>"),
    fletcher.node(
      (0, 1),
      link(theses, text([examples], size: 1.3em)),
      shape: fletcher.shapes.rect,
      stroke: black,
      inset: .6em,
    ),
    fletcher.node(
      (-1, 1),
      link(stagspider, text([stagspider], size: .8em)),
      shape: fletcher.shapes.rect,
      stroke: gray,
      inset: .5em,
    ),
    fletcher.edge("--|>"),
    fletcher.node(
      (-1, 2),
      link(generator, text([generator], size: 1.3em)),
      shape: fletcher.shapes.rect,
      stroke: black,
      inset: .6em,
    ),
    fletcher.edge((0, 0), (-1, 2), "-|>"),
    fletcher.edge((0, 1), (-1, 2), "-|>"),
    fletcher.node(
      (1, 1),
      link(htmltypst, text([htmltypst], size: .8em)),
      shape: fletcher.shapes.rect,
      stroke: gray,
      inset: .5em,
    ),
    fletcher.edge((1, -1), (1, 1), "--|>"),
    fletcher.edge("--|>"),
    fletcher.node(
      (1, 2),
      link(web, text([web], size: 1.3em)),
      shape: fletcher.shapes.rect,
      stroke: black,
      inset: .6em,
    ),
    fletcher.edge((-1, 2), (1, 2), "--|>"),
    fletcher.edge((0, 0), (1, 2), "-|>"),
    fletcher.edge((0, 1), (1, 2), "-|>"),
    fletcher.edge("--|>"),
    fletcher.node(
      (1, 3),
      link("https://typst.tul.cz/cs/", text([typst.tul.cz])),
      inset: .6em,
    ),
    fletcher.node(
      (-1, 3),
      link("https://typst.tul.cz/generate/?lang=cs", text([typst.tul.cz/generate/])),
      inset: .6em,
    ),
    fletcher.edge((-1, 2), (-1, 3), "--|>"),
  )
})

== Repos

- #link(template, [*tultemplate2*]) --- Home of the template. The template itself is developed here.
- #link(generator, [*tultemplategen*]) --- Repository of the generator. The generator is being
  developed here based on the newest template version.
- #link(web, [*tultemplate-web*]) --- Web docs for the template and the generator. Available at
  https://typst.tul.cz/en/
- #link(theses, [*tultemplate_theses*]) --- Generation of entire example documents and example code
  for the generator.
- #link(much_pdf_tools, [*much_pdf_tools*]) --- WASM tools for working with PDFs in Typst.
- #link(htmltypst, [*htmltypst*]) --- Tools for automatic typesetting of Typst code for the web.
- #link(stagspider, [*tultemplate_stagspider*]) --- Automatic crawler for STAG data. The data is
  used in the generator for easier selection of some items (like specializations).

= Template arguments

The following few pages is the complete listing of arguments accepted by this template.
If you don't have extensive knowledge of the template, we recommend rather using the generator
(https://typst.tul.cz/generate/).

== Argument listing

// Automatically generated argument list
#import "template/arguments.typ": print_argument_docs
#print_argument_docs(lang: "en")

#pagebreak(weak: true)
== Requirements

=== Implicit

The following parameters, if specified, must have an entry for the document's language:

- Author's study programme
- Author's study specialization

=== Direct

If the following parameters are specified, then the following requirements apply:

- *Abstract (`abstract`)*
  - Titles (`title`) for all languages, for which the abstract (`abstract`) is specified.

- *Acknowledgement (`acknowledgement`)*
  - Author name (`author`)

- *Keywords (`keywords`)*
  - To be displayed, the abstract for the given language must be specified.

=== Documents

The document type is defined using the `document` parameter. Documents have the following
requirements:

- *Bachelor's thesis (`bp`)*, *Project (`prj`)*
  - Abstract for all languages
  - Author name
  - If no external title pages are used
    - Document title in the document language
    - Author name
    - Author's study programme
    - Author's study specialization
    - If the document language is Czech and only a single author is specified ---
      author pronouns (`author_pronouns`) is required

- *Diploma thesis (`dp`)*
  - Abstract for all languages
  - Author name
  - If no external title pages are used
    - Document title in the document language
    - Author name
    - Author's study programme
    - If the document language is Czech and only a single author is specified ---
      author pronouns (`author_pronouns`) is required

- *Term paper (`sp`)*
  - If no external title pages are used
    - Document title in the document language
    - Author name

The remaining documents have no special requirements.
