#import "template/template.typ": *

#show: tultemplate2.with(
  lang: "en",
  title: (en: [Technical documentation of the Typst TUL template]),
  author: ([Ondřej Mekina], [Matěj Žucha]),
)

#profile("release")

= Build information

This document was built on #datetime.today().display("[year]-[month]-[day]").
#highlight[The information in this document can have discrepancies with older template versions.]
If you have a template generated by the generator or downloaded as a minimal build, check
the timestamp in `template/build_date.txt`.

= Minimal build for offline usage

If you wish to obtain a directory with just the template (without other generated files), download
the minimal build from https://typst.tul.cz/tultemplate2_minimal.zip.
#highlight[This option, however, is not recommended for begginers.]

`tultemplate2_minimal.zip` is an automatically generated file with the most recent stable template
version built for direct usage.

For automatic build you can use the following _Makefile_
(with the following tools available system-wide: _typst_, _wget_ and _unzip_).

#raw(read("./minimal.mk"), block: true, lang: "make")

This file is also available from the template repository (https://git.zumepro.cz/tul/tultemplate2)
under filename `minimal.mk`.

= Template arguments

The following few pages is the complete listing of arguments accepted by this template.
If you don't have extensive knowledge of the template, we recommend rather using the generator
(https://typst.tul.cz/generate/).

// Automatically generated argument list
#import "template/arguments.typ": print_argument_docs
#print_argument_docs(lang: "en")
